{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  name: cluster-autoscaler
  namespace: kube-system
{{- end }}
